# Site settings
name: Mikhail George
title: Mikhail George | Software Engineer
description: Software engineer focused on creating highly-scalable, distributed systems. I'm also passionate about creating products that make life a little easier
url: http://mikgeo2012.github.io
baseurl: ""
email: mikgeo2012@gmail.com
cover: img/bg-intro/bg-intro.jpg
logo:  img/logo-black.png
resume: resume.pdf
social:
  - title: email
    url: mailto:mikgeo2012@gmail.com
  - title: github
    url: https://github.com/mikgeo2012
  - title: linkedin
    url: https://www.linkedin.com/in/mikhailgeorge/
  - title: blog
    url: http://35.232.87.186/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
